# Acorn Atom Software Sources

base_path: Acorn/Atom/Software

sources:
  - name: hoglet67
    type: ddl
    url: https://github.com/hoglet67/AtomSoftwareArchive/releases/download/V13_00/AtomSoftwareArchive_20240505_1129_V13.00.zip
    folder: Software/Collections/hoglet67/main
  
  - name: blankvhd
    type: ddl
    url: https://github.com/MiSTer-devel/AcornAtom_MiSTer/raw/main/releases/blank.zip
    folder: Software/Utils

packs:
  - id: hoglet67
    name: hoglet67 
    description: hoglet67s Atom Software Collection (both as files and built into a VHD)
    estimated_size: 15.3MB
    sources: [hoglet67, blankvhd]
    build_script: MiSTer/Acorn/Atom/build.sh
    info_links:
      - label: Hoglet67s Atom Software Archive
        url: https://github.com/hoglet67/AtomSoftwareArchive
