# Commodore PET Software Sources

base_path: Commodore/PET/Software

sources:
  - name: TOSEC PET Collection
    type: ddl
    url: https://archive.org/download/PET_TOSEC_2012_04_23/PET_TOSEC_2012_04_23.zip
    folder: Disks
