# Nintendo Game Boy Software Sources

base_path: Nintendo/GameBoy/Software

sources:
  - name: No-Intro Game Boy Collection
    type: ddl
    url: https://archive.org/download/No-Intro-Collection_2016-01-03/Nintendo%20-%20Game%20Boy.zip
    folder: ROMs
