# Nintendo GBC Software Sources

base_path: Nintendo/GBC/Software

sources:
  - name: No-Intro GBC Collection
    type: ddl
    url: https://archive.org/download/No-Intro-Collection_2016-01-03/Nintendo%20-%20Game%20Boy%20Color.zip
    folder: ROMs
