# Nintendo NES Software Sources

base_path: Nintendo/NES/Software

sources:
  - name: No-Intro NES Collection
    type: ddl
    url: https://archive.org/download/No-Intro-Collection_2016-01-03/Nintendo%20-%20Nintendo%20Entertainment%20System.zip
    folder: ROMs
